'use client';

import { useState } from 'react';
import Link from 'next/link';

interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}

const FAQ_ITEMS: FAQItem[] = [
  // Getting Started
  {
    id: 'what-is-beright',
    category: 'Getting Started',
    question: 'What is BeRight?',
    answer: `BeRight is a prediction market intelligence platform that helps you trade smarter across multiple platforms (Polymarket, Kalshi, Manifold, Metaculus). We provide:\n\n• **AI-powered forecasts** - Benchmark your predictions against our ensemble AI model\n• **Arbitrage detection** - Find price discrepancies across platforms\n• **Calibration tracking** - Build your forecasting track record with Brier scores\n• **Real-time signals** - Whale movements, price alerts, and market updates\n\nThink of BeRight as your trading copilot for prediction markets.`,
  },
  {
    id: 'connect-wallet',
    category: 'Getting Started',
    question: 'How do I connect my wallet?',
    answer: `Click "Connect Wallet" on the homepage. We support:\n\n• **Phantom** - Most popular Solana wallet\n• **Solflare** - Feature-rich Solana wallet\n• **Email/Social login** - Via Privy (creates an embedded wallet)\n\nYour wallet is used for:\n1. Identity (your prediction history)\n2. On-chain vault deposits (optional)\n3. Future on-chain trading features\n\nWe never have access to your private keys.`,
  },
  {
    id: 'first-prediction',
    category: 'Getting Started',
    question: 'How do I make my first prediction?',
    answer: `**On the website:**\n1. Browse markets on the homepage or use /markets\n2. Click on a market card\n3. Enter your probability estimate (e.g., 65% YES)\n4. Add optional reasoning\n5. Submit your prediction\n\n**Via Telegram:**\n1. Message @BeRightBot\n2. Use \`/predict <topic>\` to find a market\n3. Reply with your probability\n\nYour predictions are tracked for calibration scoring. No money required to start building your track record!`,
  },
  // Scoring & Calibration
  {
    id: 'scoring',
    category: 'Scoring & Calibration',
    question: 'How does scoring work?',
    answer: `BeRight uses **Brier Scoring** - the gold standard for forecast accuracy:\n\n**Formula:** Brier Score = (probability - outcome)²\n\n**Example:**\n• You predict 80% YES, outcome is YES (1): Score = (0.80 - 1)² = 0.04 (excellent)\n• You predict 80% YES, outcome is NO (0): Score = (0.80 - 0)² = 0.64 (poor)\n\n**Score interpretation:**\n• 0.00 - 0.10: Exceptional\n• 0.10 - 0.20: Good\n• 0.20 - 0.25: Average\n• 0.25+: Below baseline\n\nLower is better. A score of 0.25 is equivalent to always guessing 50%.`,
  },
  {
    id: 'brier-score',
    category: 'Scoring & Calibration',
    question: 'What is a Brier Score?',
    answer: `The Brier Score measures how calibrated your predictions are - not just if you got the direction right, but if your confidence levels were appropriate.\n\n**Why Brier over Win Rate?**\nWin rate ignores confidence. If you say "90% YES" and it happens, great. But if you said "51% YES", that's not impressive. Brier Score captures this nuance.\n\n**What's a good Brier Score?**\n• **0.15 or lower** - Top forecaster territory\n• **0.18-0.22** - Solid performance\n• **0.25** - Random guessing baseline\n\nSuperforecasters typically achieve 0.10-0.15 on geopolitical questions.`,
  },
  {
    id: 'ai-benchmark',
    category: 'Scoring & Calibration',
    question: 'How does the AI benchmark work?',
    answer: `Every market on BeRight has an **AI probability forecast** generated by our ensemble model (GPT-4 + Claude).\n\n**How it works:**\n1. AI analyzes the market question, historical data, and current news\n2. Generates a probability estimate\n3. Your predictions are compared against the AI's\n\n**Why it matters:**\nIf you consistently beat the AI benchmark, you have demonstrable alpha. This is valuable for:\n• Building credibility as a forecaster\n• Proving skill vs. luck\n• Eventually, running signal channels others can follow`,
  },
  // Markets & Trading
  {
    id: 'resolution',
    category: 'Markets & Trading',
    question: 'How do markets resolve?',
    answer: `Markets resolve through **oracle consensus**:\n\n1. **Primary oracles** - UMA, Chainlink, or platform-native oracles\n2. **Secondary verification** - Cross-checked with authoritative sources\n3. **Dispute period** - Usually 24-48 hours for challenges\n4. **Community arbitration** - For disputed outcomes (rare)\n\n**Resolution sources by type:**\n• **Crypto prices** - CoinGecko, CoinMarketCap\n• **Elections** - AP, Reuters\n• **Sports** - ESPN, official league data\n• **Financial** - Bloomberg, FRED\n\nOnce resolved, shares pay out $1 if correct, $0 if wrong.`,
  },
  {
    id: 'arbitrage',
    category: 'Markets & Trading',
    question: 'What is arbitrage and how do I use it?',
    answer: `**Arbitrage** is when the same event has different prices on different platforms, creating a risk-free profit opportunity.\n\n**Example:**\n• Polymarket: "Trump wins" at 55¢ YES\n• Kalshi: "Trump wins" at 48¢ YES\n\nIf you buy YES on Kalshi (48¢) and NO on Polymarket (45¢), you spend 93¢ and are guaranteed $1 → 7% profit regardless of outcome.\n\n**Using BeRight:**\n• Use \`/arb\` in Telegram to scan for opportunities\n• GET \`/api/arbitrage\` for programmatic access\n• We show spreads, confidence scores, and platform links\n\n**Note:** Account for fees (~2-5%) and execution risk when calculating real profits.`,
  },
  {
    id: 'platforms',
    category: 'Markets & Trading',
    question: 'Which platforms does BeRight support?',
    answer: `We aggregate data from **5 major prediction markets:**\n\n🟣 **Polymarket** - Largest crypto-native market, USDC-based\n🟡 **Kalshi** - US-regulated (CFTC), USD deposits\n🟢 **Manifold** - Play money, great for practice\n🔴 **Metaculus** - Community forecasting, no trading\n⚪ **DFlow** - Solana-native, on-chain order books\n\n**Data available:**\n• Prices, volumes, orderbooks\n• Historical price charts\n• Cross-platform arbitrage\n• Whale activity (Polymarket)\n\nWe're adding more platforms regularly.`,
  },
  // Telegram Bot
  {
    id: 'telegram-commands',
    category: 'Telegram Bot',
    question: 'What commands does the Telegram bot support?',
    answer: `**Core Commands:**\n• \`/start\` - Welcome message\n• \`/help\` - List all commands\n• \`/brief\` - Morning market briefing\n• \`/hot\` - Trending markets\n\n**Intelligence:**\n• \`/arb\` - Arbitrage scanner\n• \`/research <topic>\` - Deep analysis\n• \`/intel <topic>\` - News & sentiment\n• \`/whale\` - Smart money activity\n\n**Trading:**\n• \`/predict <topic>\` - Make a prediction\n• \`/me\` - Your stats & calibration\n• \`/calibration\` - Detailed accuracy report\n• \`/leaderboard\` - Top forecasters\n\n**Kalshi:**\n• \`/kbalance\` - Account balance\n• \`/kpositions\` - Open positions\n• \`/kbuy <ticker> YES/NO <amount>\` - Buy shares`,
  },
  {
    id: 'alerts',
    category: 'Telegram Bot',
    question: 'How do I set up alerts?',
    answer: `**Subscribe to signal channels:**\n\`/subscribe-all\` - Get all signal types:\n• Arbitrage opportunities (>3% spread)\n• Whale movements (>$10K)\n• Price alerts\n• Market resolutions\n\n**Custom alerts (coming soon):**\n• Price threshold alerts\n• Market-specific notifications\n• Portfolio P&L alerts\n\n**Unsubscribe:**\n\`/unsubscribe\` - Stop receiving alerts\n\n**Note:** Alerts are sent to your Telegram DM with @BeRightBot.`,
  },
  {
    id: 'link-wallet',
    category: 'Telegram Bot',
    question: 'How do I link my wallet to Telegram?',
    answer: `**Step 1:** Message @BeRightBot on Telegram\n\n**Step 2:** Use \`/link <wallet-address>\`\nExample: \`/link 7xKX...abc\`\n\n**Step 3:** Verify ownership (if required)\n• Sign a message with your wallet\n• Paste the signature to the bot\n\n**What linking enables:**\n• Unified prediction history\n• Portfolio sync across web & Telegram\n• Wallet-based leaderboard ranking\n• Future: execute trades from Telegram\n\nYour Telegram ID and wallet are stored securely. We never access your funds.`,
  },
  // Technical
  {
    id: 'api-access',
    category: 'Technical',
    question: 'How do I access the API?',
    answer: `BeRight offers **free public API access** for most endpoints:\n\n**No authentication required:**\n• \`GET /api/markets\` - Search markets\n• \`GET /api/arbitrage\` - Arbitrage scanner\n• \`GET /api/leaderboard\` - Top forecasters\n• \`GET /api/forecasters\` - Forecaster profiles\n\n**Rate limits:**\n• 100 requests/minute for anonymous\n• 1000 requests/minute with API key (coming soon)\n\n**Example:**\n\`\`\`\ncurl https://beright.io/api/markets?hot=true&limit=10\n\`\`\`\n\nSee our [API Documentation](/docs/api) for full details.`,
  },
  {
    id: 'data-sources',
    category: 'Technical',
    question: 'Where does BeRight get its data?',
    answer: `We aggregate from multiple sources:\n\n**Market Data:**\n• Polymarket GraphQL API\n• Kalshi REST API\n• Manifold REST API\n• Metaculus API\n• DFlow on-chain data\n\n**News & Sentiment:**\n• Twitter/X (via API)\n• Reddit\n• News APIs (Tavily, NewsAPI)\n\n**On-chain:**\n• Solana RPC (Helius)\n• Wallet activity tracking\n\n**AI Analysis:**\n• OpenAI GPT-4\n• Anthropic Claude\n• Custom embeddings (OpenAI)\n\nData refreshes every 30-60 seconds for active markets.`,
  },
  {
    id: 'vault',
    category: 'Technical',
    question: 'What is the BeRight Vault?',
    answer: `The BeRight Vault is an **on-chain smart contract** on Solana that allows secure fund management:\n\n**Features:**\n• Deposit SOL with timelock protection\n• Set withdrawal delays (e.g., 24h waiting period)\n• Guardian system for large withdrawals\n• Epoch-based withdrawal limits\n• Freeze/unfreeze capability\n\n**Use cases:**\n• Secure savings for trading\n• Self-custody with extra security layers\n• Future: automated trading from vault\n\n**Contract:** Deployed on Solana devnet (mainnet coming soon)\n\nThe vault is fully non-custodial - only you control your funds.`,
  },
];

const CATEGORIES = [...new Set(FAQ_ITEMS.map(item => item.category))];

export default function FAQPage() {
  const [openItems, setOpenItems] = useState<Set<string>>(new Set());
  const [activeCategory, setActiveCategory] = useState<string>('all');

  const toggleItem = (id: string) => {
    setOpenItems(prev => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const filteredItems = activeCategory === 'all'
    ? FAQ_ITEMS
    : FAQ_ITEMS.filter(item => item.category === activeCategory);

  return (
    <div className="faq-page">
      {/* Header */}
      <header className="docs-header">
        <Link href="/" className="logo">
          <span className="logo-be">Be</span>
          <span className="logo-right">Right</span>
        </Link>
        <nav className="nav-links">
          <Link href="/docs" className="nav-link">Docs</Link>
          <Link href="/docs/api" className="nav-link">API</Link>
          <Link href="/docs/faq" className="nav-link active">FAQ</Link>
        </nav>
      </header>

      {/* Hero */}
      <section className="faq-hero">
        <h1>Frequently Asked Questions</h1>
        <p>Everything you need to know about BeRight</p>
      </section>

      {/* Category Filter */}
      <div className="category-filter">
        <button
          className={`cat-btn ${activeCategory === 'all' ? 'active' : ''}`}
          onClick={() => setActiveCategory('all')}
        >
          All
        </button>
        {CATEGORIES.map(cat => (
          <button
            key={cat}
            className={`cat-btn ${activeCategory === cat ? 'active' : ''}`}
            onClick={() => setActiveCategory(cat)}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* FAQ List */}
      <section className="faq-list">
        {filteredItems.map(item => (
          <div
            key={item.id}
            id={item.id}
            className={`faq-item ${openItems.has(item.id) ? 'open' : ''}`}
          >
            <button className="faq-question" onClick={() => toggleItem(item.id)}>
              <span className="faq-category-tag">{item.category}</span>
              <span className="faq-q-text">{item.question}</span>
              <span className="faq-toggle">{openItems.has(item.id) ? '−' : '+'}</span>
            </button>
            {openItems.has(item.id) && (
              <div className="faq-answer">
                {item.answer.split('\n').map((line, i) => {
                  // Handle bold text
                  const parts = line.split(/\*\*(.*?)\*\*/g);
                  return (
                    <p key={i}>
                      {parts.map((part, j) =>
                        j % 2 === 1 ? <strong key={j}>{part}</strong> : part
                      )}
                    </p>
                  );
                })}
              </div>
            )}
          </div>
        ))}
      </section>

      {/* CTA */}
      <section className="faq-cta">
        <h2>Still have questions?</h2>
        <p>Join our community or check out the API docs</p>
        <div className="cta-buttons">
          <a href="https://discord.gg/beright" className="cta-btn primary" target="_blank" rel="noopener">
            Join Discord
          </a>
          <Link href="/docs/api" className="cta-btn secondary">
            API Documentation
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="docs-footer">
        <div className="footer-brand">
          <span className="logo-be">Be</span>
          <span className="logo-right">Right</span>
        </div>
        <div className="footer-links">
          <a href="https://twitter.com/beright" target="_blank" rel="noopener">Twitter</a>
          <a href="https://discord.gg/beright" target="_blank" rel="noopener">Discord</a>
          <a href="https://t.me/berightbot" target="_blank" rel="noopener">Telegram</a>
        </div>
      </footer>

      <style jsx>{`
        .faq-page {
          min-height: 100vh;
          background: #030305;
          color: #fff;
          font-family: 'Outfit', system-ui, sans-serif;
        }

        /* Header */
        .docs-header {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 20px 40px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.06);
        }

        .logo {
          display: flex;
          text-decoration: none;
          font-size: 22px;
          font-weight: 800;
        }

        .logo-be { color: #fff; }
        .logo-right {
          background: linear-gradient(135deg, #00E676, #00B0FF, #8B5CF6);
          -webkit-background-clip: text;
          background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .nav-links {
          display: flex;
          gap: 32px;
        }

        .nav-link {
          color: rgba(255, 255, 255, 0.6);
          text-decoration: none;
          font-size: 14px;
          font-weight: 500;
          transition: color 0.2s;
        }

        .nav-link:hover, .nav-link.active {
          color: #fff;
        }

        /* Hero */
        .faq-hero {
          text-align: center;
          padding: 80px 24px 40px;
        }

        .faq-hero h1 {
          font-size: 42px;
          font-weight: 800;
          margin: 0 0 12px;
          letter-spacing: -1px;
        }

        .faq-hero p {
          font-size: 18px;
          color: rgba(255, 255, 255, 0.6);
          margin: 0;
        }

        /* Category Filter */
        .category-filter {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 10px;
          padding: 0 24px 40px;
          flex-wrap: wrap;
        }

        .cat-btn {
          padding: 10px 18px;
          background: rgba(255, 255, 255, 0.04);
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 10px;
          color: rgba(255, 255, 255, 0.7);
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
          font-family: inherit;
        }

        .cat-btn:hover {
          background: rgba(255, 255, 255, 0.08);
          color: #fff;
        }

        .cat-btn.active {
          background: linear-gradient(135deg, rgba(0, 230, 118, 0.15), rgba(0, 176, 255, 0.15));
          border-color: rgba(0, 230, 118, 0.3);
          color: #00E676;
        }

        /* FAQ List */
        .faq-list {
          max-width: 800px;
          margin: 0 auto;
          padding: 0 24px 60px;
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .faq-item {
          background: rgba(255, 255, 255, 0.02);
          border: 1px solid rgba(255, 255, 255, 0.06);
          border-radius: 12px;
          overflow: hidden;
          transition: border-color 0.2s;
        }

        .faq-item.open {
          border-color: rgba(0, 230, 118, 0.2);
        }

        .faq-question {
          width: 100%;
          display: flex;
          align-items: center;
          gap: 12px;
          padding: 18px 20px;
          background: transparent;
          border: none;
          color: #fff;
          font-size: 15px;
          font-weight: 600;
          text-align: left;
          cursor: pointer;
          font-family: inherit;
          transition: background 0.2s;
        }

        .faq-question:hover {
          background: rgba(255, 255, 255, 0.02);
        }

        .faq-category-tag {
          padding: 4px 10px;
          background: rgba(139, 92, 246, 0.15);
          border-radius: 6px;
          font-size: 11px;
          font-weight: 600;
          color: #A78BFA;
          white-space: nowrap;
        }

        .faq-q-text {
          flex: 1;
        }

        .faq-toggle {
          width: 24px;
          height: 24px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(255, 255, 255, 0.06);
          border-radius: 6px;
          font-size: 18px;
          color: rgba(255, 255, 255, 0.5);
        }

        .faq-item.open .faq-toggle {
          background: rgba(0, 230, 118, 0.15);
          color: #00E676;
        }

        .faq-answer {
          padding: 0 20px 20px;
          font-size: 14px;
          line-height: 1.7;
          color: rgba(255, 255, 255, 0.75);
        }

        .faq-answer p {
          margin: 0 0 12px;
        }

        .faq-answer p:last-child {
          margin-bottom: 0;
        }

        .faq-answer strong {
          color: #fff;
          font-weight: 600;
        }

        /* CTA */
        .faq-cta {
          text-align: center;
          padding: 60px 24px 80px;
          background: linear-gradient(180deg, transparent 0%, rgba(139, 92, 246, 0.03) 100%);
        }

        .faq-cta h2 {
          font-size: 28px;
          font-weight: 700;
          margin: 0 0 8px;
        }

        .faq-cta p {
          font-size: 16px;
          color: rgba(255, 255, 255, 0.6);
          margin: 0 0 28px;
        }

        .cta-buttons {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 16px;
          flex-wrap: wrap;
        }

        .cta-btn {
          padding: 14px 28px;
          border-radius: 12px;
          font-size: 15px;
          font-weight: 600;
          text-decoration: none;
          transition: all 0.2s;
        }

        .cta-btn.primary {
          background: linear-gradient(135deg, #00E676, #00C853);
          color: #000;
        }

        .cta-btn.primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 24px rgba(0, 230, 118, 0.3);
        }

        .cta-btn.secondary {
          background: rgba(255, 255, 255, 0.06);
          border: 1px solid rgba(255, 255, 255, 0.15);
          color: #fff;
        }

        .cta-btn.secondary:hover {
          background: rgba(255, 255, 255, 0.1);
        }

        /* Footer */
        .docs-footer {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 30px 40px;
          border-top: 1px solid rgba(255, 255, 255, 0.06);
        }

        .footer-brand {
          font-size: 18px;
          font-weight: 800;
        }

        .footer-links {
          display: flex;
          gap: 24px;
        }

        .footer-links a {
          color: rgba(255, 255, 255, 0.5);
          text-decoration: none;
          font-size: 14px;
          transition: color 0.2s;
        }

        .footer-links a:hover {
          color: #fff;
        }

        @media (max-width: 768px) {
          .docs-header {
            padding: 16px 20px;
          }

          .faq-hero h1 {
            font-size: 28px;
          }

          .faq-question {
            flex-wrap: wrap;
          }

          .faq-category-tag {
            order: 1;
            margin-bottom: 8px;
          }

          .faq-q-text {
            order: 3;
            width: 100%;
          }

          .faq-toggle {
            order: 2;
            margin-left: auto;
          }

          .docs-footer {
            flex-direction: column;
            gap: 20px;
            text-align: center;
          }
        }
      `}</style>
    </div>
  );
}
