'use client';

import { useState } from 'react';
import Link from 'next/link';
import Header from '@/components/Header';

interface FAQItem {
  id: string;
  question: string;
  answer: string;
  category: string;
}

const FAQ_ITEMS: FAQItem[] = [
  // Getting Started
  {
    id: 'what-is-beright',
    category: 'Getting Started',
    question: 'What is BeRight?',
    answer: `BeRight is a prediction market intelligence platform that helps you trade smarter across multiple platforms (Polymarket, Kalshi, Manifold, Metaculus). We provide:\n\n• **AI-powered forecasts** - Benchmark your predictions against our ensemble AI model\n• **Arbitrage detection** - Find price discrepancies across platforms\n• **Calibration tracking** - Build your forecasting track record with Brier scores\n• **Real-time signals** - Whale movements, price alerts, and market updates\n\nThink of BeRight as your trading copilot for prediction markets.`,
  },
  {
    id: 'connect-wallet',
    category: 'Getting Started',
    question: 'How do I connect my wallet?',
    answer: `Click "Connect Wallet" on the homepage. We support:\n\n• **Phantom** - Most popular Solana wallet\n• **Solflare** - Feature-rich Solana wallet\n• **Email/Social login** - Via Privy (creates an embedded wallet)\n\nYour wallet is used for:\n1. Identity (your prediction history)\n2. On-chain vault deposits (optional)\n3. Future on-chain trading features\n\nWe never have access to your private keys.`,
  },
  // Scoring & Calibration
  {
    id: 'scoring',
    category: 'Scoring & Calibration',
    question: 'How does scoring work?',
    answer: `BeRight uses **Brier Scoring** - the gold standard for forecast accuracy:\n\n**Formula:** Brier Score = (probability - outcome)²\n\n**Example:**\n• You predict 80% YES, outcome is YES (1): Score = (0.80 - 1)² = 0.04 (excellent)\n• You predict 80% YES, outcome is NO (0): Score = (0.80 - 0)² = 0.64 (poor)\n\n**Score interpretation:**\n• 0.00 - 0.10: Exceptional\n• 0.10 - 0.20: Good\n• 0.20 - 0.25: Average\n• 0.25+: Below baseline\n\nLower is better. A score of 0.25 is equivalent to always guessing 50%.`,
  },
  {
    id: 'brier-score',
    category: 'Scoring & Calibration',
    question: 'What is a Brier Score?',
    answer: `The Brier Score measures how calibrated your predictions are - not just if you got the direction right, but if your confidence levels were appropriate.\n\n**Why Brier over Win Rate?**\nWin rate ignores confidence. If you say "90% YES" and it happens, great. But if you said "51% YES", that's not impressive. Brier Score captures this nuance.\n\n**What's a good Brier Score?**\n• **0.15 or lower** - Top forecaster territory\n• **0.18-0.22** - Solid performance\n• **0.25** - Random guessing baseline\n\nSuperforecasters typically achieve 0.10-0.15 on geopolitical questions.`,
  },
  {
    id: 'ai-benchmark',
    category: 'Scoring & Calibration',
    question: 'How does the AI benchmark work?',
    answer: `Every market on BeRight has an **AI probability forecast** generated by our ensemble model (GPT-4 + Claude).\n\n**How it works:**\n1. AI analyzes the market question, historical data, and current news\n2. Generates a probability estimate\n3. Your predictions are compared against the AI's\n\n**Why it matters:**\nIf you consistently beat the AI benchmark, you have demonstrable alpha. This is valuable for:\n• Building credibility as a forecaster\n• Proving skill vs. luck\n• Eventually, running signal channels others can follow`,
  },
  // Markets & Trading
  {
    id: 'arbitrage',
    category: 'Markets & Trading',
    question: 'What is arbitrage and how do I use it?',
    answer: `**Arbitrage** is when the same event has different prices on different platforms, creating a risk-free profit opportunity.\n\n**Example:**\n• Polymarket: "Trump wins" at 55¢ YES\n• Kalshi: "Trump wins" at 48¢ YES\n\nIf you buy YES on Kalshi (48¢) and NO on Polymarket (45¢), you spend 93¢ and are guaranteed $1 → 7% profit regardless of outcome.\n\n**Using BeRight:**\n• Use \`/arb\` in Telegram to scan for opportunities\n• GET \`/api/arbitrage\` for programmatic access\n• We show spreads, confidence scores, and platform links\n\n**Note:** Account for fees (~2-5%) and execution risk when calculating real profits.`,
  },
  {
    id: 'platforms',
    category: 'Markets & Trading',
    question: 'Which platforms does BeRight support?',
    answer: `We aggregate data from **5 major prediction markets:**\n\n🟣 **Polymarket** - Largest crypto-native market, USDC-based\n🟡 **Kalshi** - US-regulated (CFTC), USD deposits\n🟢 **Manifold** - Play money, great for practice\n🔴 **Metaculus** - Community forecasting, no trading\n⚪ **DFlow** - Solana-native, on-chain order books\n\n**Data available:**\n• Prices, volumes, orderbooks\n• Historical price charts\n• Cross-platform arbitrage\n• Whale activity (Polymarket)\n\nWe're adding more platforms regularly.`,
  },
  // Telegram Bot
  {
    id: 'telegram-commands',
    category: 'Telegram Bot',
    question: 'What commands does the Telegram bot support?',
    answer: `**Core Commands:**\n• \`/start\` - Welcome message\n• \`/help\` - List all commands\n• \`/brief\` - Morning market briefing\n• \`/hot\` - Trending markets\n\n**Intelligence:**\n• \`/arb\` - Arbitrage scanner\n• \`/research <topic>\` - Deep analysis\n• \`/intel <topic>\` - News & sentiment\n• \`/whale\` - Smart money activity\n\n**Trading:**\n• \`/predict <topic>\` - Make a prediction\n• \`/me\` - Your stats & calibration\n• \`/calibration\` - Detailed accuracy report\n• \`/leaderboard\` - Top forecasters\n\n**Kalshi:**\n• \`/kbalance\` - Account balance\n• \`/kpositions\` - Open positions\n• \`/kbuy <ticker> YES/NO <amount>\` - Buy shares`,
  },
  {
    id: 'alerts',
    category: 'Telegram Bot',
    question: 'How do I set up alerts?',
    answer: `**Subscribe to signal channels:**\n\`/subscribe-all\` - Get all signal types:\n• Arbitrage opportunities (>3% spread)\n• Whale movements (>$10K)\n• Price alerts\n• Market resolutions\n\n**Custom alerts (coming soon):**\n• Price threshold alerts\n• Market-specific notifications\n• Portfolio P&L alerts\n\n**Unsubscribe:**\n\`/unsubscribe\` - Stop receiving alerts\n\n**Note:** Alerts are sent to your Telegram DM with @BeRightBot.`,
  },
];

const CATEGORIES = [...new Set(FAQ_ITEMS.map(item => item.category))];

// Category color mapping
const CATEGORY_COLORS: Record<string, { bg: string; border: string; text: string }> = {
  'Getting Started': { bg: 'rgba(0, 255, 136, 0.12)', border: 'rgba(0, 255, 136, 0.25)', text: '#00FF88' },
  'Scoring & Calibration': { bg: 'rgba(255, 193, 7, 0.12)', border: 'rgba(255, 193, 7, 0.25)', text: '#FFC107' },
  'Markets & Trading': { bg: 'rgba(0, 176, 255, 0.12)', border: 'rgba(0, 176, 255, 0.25)', text: '#00B0FF' },
  'Telegram Bot': { bg: 'rgba(0, 136, 204, 0.12)', border: 'rgba(0, 136, 204, 0.25)', text: '#0088CC' },
  'Technical': { bg: 'rgba(156, 163, 175, 0.12)', border: 'rgba(156, 163, 175, 0.25)', text: '#9CA3AF' },
};

export default function FAQPage() {
  // Auto-expand first two questions by default
  const [openItems, setOpenItems] = useState<Set<string>>(new Set(['what-is-beright', 'scoring']));
  const [activeCategory, setActiveCategory] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');

  const toggleItem = (id: string) => {
    setOpenItems(prev => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  // Filter by category and search query
  const filteredItems = FAQ_ITEMS.filter(item => {
    const matchesCategory = activeCategory === 'all' || item.category === activeCategory;
    const matchesSearch = searchQuery === '' ||
      item.question.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.answer.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="faq-page">
      <Header />

      {/* Hero */}
      <section className="faq-hero">
        <h1>Frequently Asked Questions</h1>
        <p>Quick answers on markets, scoring, the bot, and API</p>

        {/* Search */}
        <div className="search-wrapper">
          <svg className="search-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <circle cx="11" cy="11" r="8" />
            <path d="M21 21l-4.35-4.35" />
          </svg>
          <input
            type="text"
            className="search-input"
            placeholder="Search questions..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          {searchQuery && (
            <button className="search-clear" onClick={() => setSearchQuery('')}>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M18 6L6 18M6 6l12 12" />
              </svg>
            </button>
          )}
        </div>
      </section>

      {/* Category Filter */}
      <div className="category-filter">
        <button
          className={`cat-btn ${activeCategory === 'all' ? 'active' : ''}`}
          onClick={() => setActiveCategory('all')}
        >
          All
        </button>
        {CATEGORIES.map(cat => (
          <button
            key={cat}
            className={`cat-btn ${activeCategory === cat ? 'active' : ''}`}
            onClick={() => setActiveCategory(cat)}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* FAQ List */}
      <section className="faq-list">
        {filteredItems.length === 0 ? (
          <div className="no-results">
            <p>No questions found matching "{searchQuery}"</p>
            <button onClick={() => setSearchQuery('')}>Clear search</button>
          </div>
        ) : (
          filteredItems.map(item => {
            const colors = CATEGORY_COLORS[item.category] || CATEGORY_COLORS['Technical'];
            return (
              <div
                key={item.id}
                id={item.id}
                className={`faq-item ${openItems.has(item.id) ? 'open' : ''}`}
              >
                <button className="faq-question" onClick={() => toggleItem(item.id)}>
                  <span
                    className="faq-category-tag"
                    style={{
                      background: colors.bg,
                      borderColor: colors.border,
                      color: colors.text,
                    }}
                  >
                    {item.category}
                  </span>
                  <span className="faq-q-text">{item.question}</span>
                  <span className="faq-toggle">{openItems.has(item.id) ? '−' : '+'}</span>
                </button>
                {openItems.has(item.id) && (
                  <div className="faq-answer">
                    {item.answer.split('\n').map((line, i) => {
                      // Handle bold text
                      const parts = line.split(/\*\*(.*?)\*\*/g);
                      return (
                        <p key={i}>
                          {parts.map((part, j) =>
                            j % 2 === 1 ? <strong key={j}>{part}</strong> : part
                          )}
                        </p>
                      );
                    })}
                  </div>
                )}
              </div>
            );
          })
        )}
      </section>

      {/* CTA */}
      <section className="faq-cta">
        <h2>Still have questions?</h2>
        <p>Join our Telegram community or try the bot</p>
        <div className="cta-buttons">
          <a href="https://t.me/berightaii" className="cta-btn primary" target="_blank" rel="noopener noreferrer">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69a.2.2 0 00-.05-.18c-.06-.05-.14-.03-.21-.02-.09.02-1.49.95-4.22 2.79-.4.27-.76.41-1.08.4-.36-.01-1.04-.2-1.55-.37-.63-.2-1.12-.31-1.08-.66.02-.18.27-.36.74-.55 2.92-1.27 4.86-2.11 5.83-2.51 2.78-1.16 3.35-1.36 3.73-1.36.08 0 .27.02.39.12.1.08.13.19.14.27-.01.06.01.24 0 .38z"/>
            </svg>
            Open @berightbot
          </a>
          <Link href="/docs" className="cta-btn secondary">
            Back to Docs
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="docs-footer">
        <div className="footer-brand">
          <span className="logo-icon">◉</span>
          <span>BeRight</span>
        </div>
        <div className="footer-links">
          <a href="https://t.me/berightaii" target="_blank" rel="noopener noreferrer">Telegram</a>
          <a href="https://x.com/AgentBEright" target="_blank" rel="noopener noreferrer">Twitter</a>
        </div>
        <p className="footer-copyright">© 2026 BeRight Protocol</p>
      </footer>

      <style jsx>{`
        .faq-page {
          min-height: 100vh;
          background: #0A0A0B;
          color: #fff;
          font-family: 'Satoshi', system-ui, sans-serif;
        }

        /* Hero */
        .faq-hero {
          text-align: center;
          padding: 120px 24px 40px;
        }

        .faq-hero h1 {
          font-size: 42px;
          font-weight: 800;
          margin: 0 0 12px;
          letter-spacing: -1px;
        }

        .faq-hero p {
          font-size: 18px;
          color: rgba(255, 255, 255, 0.6);
          margin: 0 0 28px;
        }

        /* Search */
        .search-wrapper {
          position: relative;
          max-width: 480px;
          margin: 0 auto;
        }

        .search-icon {
          position: absolute;
          left: 16px;
          top: 50%;
          transform: translateY(-50%);
          color: rgba(255, 255, 255, 0.4);
        }

        .search-input {
          width: 100%;
          padding: 14px 44px;
          background: rgba(255, 255, 255, 0.04);
          border: 1px solid rgba(255, 255, 255, 0.1);
          border-radius: 12px;
          color: #fff;
          font-size: 15px;
          font-family: inherit;
          outline: none;
          transition: all 0.2s ease;
        }

        .search-input::placeholder {
          color: rgba(255, 255, 255, 0.4);
        }

        .search-input:focus {
          border-color: rgba(0, 255, 136, 0.3);
          background: rgba(255, 255, 255, 0.06);
        }

        .search-clear {
          position: absolute;
          right: 12px;
          top: 50%;
          transform: translateY(-50%);
          width: 28px;
          height: 28px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(255, 255, 255, 0.1);
          border: none;
          border-radius: 6px;
          color: rgba(255, 255, 255, 0.6);
          cursor: pointer;
        }

        .search-clear:hover {
          background: rgba(255, 255, 255, 0.15);
          color: #fff;
        }

        /* Category Filter */
        .category-filter {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 10px;
          padding: 0 24px 40px;
          overflow-x: auto;
          -webkit-overflow-scrolling: touch;
          scrollbar-width: none;
        }

        .category-filter::-webkit-scrollbar {
          display: none;
        }

        .cat-btn {
          padding: 10px 18px;
          background: rgba(255, 255, 255, 0.04);
          border: 1px solid rgba(255, 255, 255, 0.08);
          border-radius: 10px;
          color: rgba(255, 255, 255, 0.7);
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          transition: all 0.2s;
          font-family: inherit;
        }

        .cat-btn:hover {
          background: rgba(255, 255, 255, 0.08);
          color: #fff;
        }

        .cat-btn.active {
          background: linear-gradient(135deg, rgba(0, 230, 118, 0.15), rgba(0, 176, 255, 0.15));
          border-color: rgba(0, 230, 118, 0.3);
          color: #00FF88;
        }

        /* FAQ List */
        .faq-list {
          max-width: 800px;
          margin: 0 auto;
          padding: 0 24px 60px;
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .faq-item {
          background: rgba(255, 255, 255, 0.02);
          border: 1px solid rgba(255, 255, 255, 0.06);
          border-radius: 12px;
          overflow: hidden;
          transition: border-color 0.2s;
        }

        .faq-item.open {
          border-color: rgba(0, 230, 118, 0.2);
        }

        .faq-question {
          width: 100%;
          display: flex;
          align-items: center;
          gap: 14px;
          padding: 18px 20px;
          background: transparent;
          border: none;
          color: #fff;
          font-size: 15px;
          font-weight: 600;
          text-align: left;
          cursor: pointer;
          font-family: inherit;
          transition: background 0.2s;
        }

        .faq-question:hover {
          background: rgba(255, 255, 255, 0.02);
        }

        .faq-category-tag {
          padding: 5px 10px;
          border: 1px solid;
          border-radius: 6px;
          font-size: 11px;
          font-weight: 600;
          white-space: nowrap;
          flex-shrink: 0;
        }

        .faq-q-text {
          flex: 1;
          text-align: left;
        }

        .faq-toggle {
          width: 28px;
          height: 28px;
          display: flex;
          align-items: center;
          justify-content: center;
          background: rgba(255, 255, 255, 0.06);
          border-radius: 8px;
          font-size: 18px;
          color: rgba(255, 255, 255, 0.5);
          flex-shrink: 0;
          margin-left: auto;
          transition: all 0.2s ease;
        }

        .faq-item.open .faq-toggle {
          background: rgba(0, 255, 136, 0.15);
          color: #00FF88;
        }

        /* No Results */
        .no-results {
          text-align: center;
          padding: 60px 20px;
          color: rgba(255, 255, 255, 0.5);
        }

        .no-results p {
          margin: 0 0 16px;
        }

        .no-results button {
          padding: 10px 20px;
          background: rgba(0, 255, 136, 0.1);
          border: 1px solid rgba(0, 255, 136, 0.2);
          border-radius: 8px;
          color: #00FF88;
          font-size: 14px;
          font-weight: 600;
          cursor: pointer;
          font-family: inherit;
        }

        .faq-answer {
          padding: 0 20px 20px;
          font-size: 14px;
          line-height: 1.7;
          color: rgba(255, 255, 255, 0.75);
        }

        .faq-answer p {
          margin: 0 0 12px;
        }

        .faq-answer p:last-child {
          margin-bottom: 0;
        }

        .faq-answer strong {
          color: #fff;
          font-weight: 600;
        }

        /* CTA */
        .faq-cta {
          text-align: center;
          padding: 60px 24px 80px;
          background: linear-gradient(180deg, transparent 0%, rgba(139, 92, 246, 0.03) 100%);
        }

        .faq-cta h2 {
          font-size: 28px;
          font-weight: 700;
          margin: 0 0 8px;
        }

        .faq-cta p {
          font-size: 16px;
          color: rgba(255, 255, 255, 0.6);
          margin: 0 0 28px;
        }

        .cta-buttons {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 16px;
          flex-wrap: wrap;
        }

        .cta-btn {
          display: inline-flex;
          align-items: center;
          gap: 10px;
          padding: 14px 28px;
          border-radius: 12px;
          font-size: 15px;
          font-weight: 600;
          text-decoration: none;
          transition: all 0.2s;
        }

        .cta-btn.primary {
          background: linear-gradient(135deg, #00FF88, #00D4FF);
          color: #000;
        }

        .cta-btn.primary:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 24px rgba(0, 255, 136, 0.3);
        }

        .cta-btn.secondary {
          background: rgba(255, 255, 255, 0.06);
          border: 1px solid rgba(255, 255, 255, 0.15);
          color: #fff;
        }

        .cta-btn.secondary:hover {
          background: rgba(255, 255, 255, 0.1);
        }

        /* Footer */
        .docs-footer {
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 30px 40px;
          border-top: 1px solid rgba(255, 255, 255, 0.06);
        }

        .footer-brand {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 18px;
          font-weight: 800;
        }

        .footer-brand .logo-icon {
          color: #00FF88;
        }

        .footer-copyright {
          font-size: 13px;
          color: rgba(255, 255, 255, 0.3);
          margin: 0;
        }

        .footer-links {
          display: flex;
          gap: 24px;
        }

        .footer-links a {
          color: rgba(255, 255, 255, 0.5);
          text-decoration: none;
          font-size: 14px;
          transition: color 0.2s;
        }

        .footer-links a:hover {
          color: #fff;
        }

        @media (max-width: 768px) {
          .faq-hero {
            padding-top: 100px;
          }

          .faq-hero h1 {
            font-size: 28px;
          }

          .faq-question {
            flex-wrap: wrap;
          }

          .faq-category-tag {
            order: 1;
            margin-bottom: 8px;
          }

          .faq-q-text {
            order: 3;
            width: 100%;
          }

          .faq-toggle {
            order: 2;
            margin-left: auto;
          }

          .docs-footer {
            flex-direction: column;
            gap: 20px;
            text-align: center;
          }
        }
      `}</style>
    </div>
  );
}
