[workspace]
resolver = "2"
members = ["programs/conviction-escrow"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anchor-lang = "0.32.0"
anchor-spl = "0.32.0"
blake3 = "=1.5.5"
indexmap = "=2.7.1"
proc-macro-crate = "=3.2.0"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
