/**
 * Real Leaderboard API Route
 *
 * Serves real forecaster data from Metaculus and Polymarket
 * with BeRight Scoring V3
 */

import { NextResponse } from 'next/server';
import * as fs from 'fs/promises';
import * as path from 'path';

export async function GET() {
  try {
    // Read the real leaderboard data generated by the scoring engine
    const dataPath = path.join(process.cwd(), 'public', 'data', 'real-leaderboard.json');

    // Check if file exists
    try {
      await fs.access(dataPath);
    } catch {
      // File doesn't exist, return empty leaderboard
      return NextResponse.json({
        success: true,
        data: {
          leaderboard: [],
          total: 0,
          message: 'No real leaderboard data available. Run `npm run fetch:real` in forecaster-scoring-engine to generate.',
        },
      });
    }

    // Read and parse the file
    const fileContent = await fs.readFile(dataPath, 'utf-8');
    const leaderboard = JSON.parse(fileContent);

    return NextResponse.json({
      success: true,
      data: {
        leaderboard,
        total: leaderboard.length,
        lastUpdated: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error('Error fetching real leaderboard:', error);

    return NextResponse.json(
      {
        success: false,
        error: 'Failed to fetch real leaderboard data',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

/**
 * POST endpoint to trigger leaderboard recalculation
 * (Optional - for future use)
 */
export async function POST() {
  // This would trigger the scoring engine to recalculate
  // For now, return a message to run manually
  return NextResponse.json({
    success: false,
    message: 'To recalculate leaderboard, run: cd forecaster-scoring-engine && npm run fetch:real',
  });
}
