/**
 * Tests for brief.ts
 * Auto-generated by BeRight Builder
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import { generateMorningBrief } from './brief';
import { formatBriefTelegram } from './brief';
import { formatBriefWeb } from './brief';
import { formatBriefText } from './brief';
import { morningBrief } from './brief';
import { quickBrief } from './brief';

describe('brief', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });


  describe('generateMorningBrief', () => {
    it('should be defined', () => {
      expect(generateMorningBrief).toBeDefined();
    });

    it('should return a SkillResponse', async () => {
      const result = await generateMorningBrief();
      expect(result).toHaveProperty('text');
      expect(result).toHaveProperty('mood');
    });
  });


  describe('formatBriefTelegram', () => {
    it('should be defined', () => {
      expect(formatBriefTelegram).toBeDefined();
    });

    it('should return a SkillResponse', async () => {
      const result = await formatBriefTelegram();
      expect(result).toHaveProperty('text');
      expect(result).toHaveProperty('mood');
    });
  });


  describe('formatBriefWeb', () => {
    it('should be defined', () => {
      expect(formatBriefWeb).toBeDefined();
    });

    it('should return a SkillResponse', async () => {
      const result = await formatBriefWeb();
      expect(result).toHaveProperty('text');
      expect(result).toHaveProperty('mood');
    });
  });


  describe('formatBriefText', () => {
    it('should be defined', () => {
      expect(formatBriefText).toBeDefined();
    });

    it('should return a SkillResponse', async () => {
      const result = await formatBriefText();
      expect(result).toHaveProperty('text');
      expect(result).toHaveProperty('mood');
    });
  });


  describe('morningBrief', () => {
    it('should be defined', () => {
      expect(morningBrief).toBeDefined();
    });

    it('should return a SkillResponse', async () => {
      const result = await morningBrief();
      expect(result).toHaveProperty('text');
      expect(result).toHaveProperty('mood');
    });
  });


  describe('quickBrief', () => {
    it('should be defined', () => {
      expect(quickBrief).toBeDefined();
    });

    it('should return a SkillResponse', async () => {
      const result = await quickBrief();
      expect(result).toHaveProperty('text');
      expect(result).toHaveProperty('mood');
    });
  });

});
